alquileres/urls.py
from django.urls import path
from . import views

app_name = "alquileres"

urlpatterns = [
    path("", views.alquileres, name="alquileres"),
    path("nuevo/<int:item_id>", views.nuevo_alquiler, name="nuevo_alquiler"),
    path("<int:id>/", views.alquiler_detalle, name="alquiler_detalle"),
    path("confirmar/<int:id>", views.confirmar_alquiler, name="confirmar_alquiler"),
    path("enviar-correo/<int:id>", views.enviar_correo_alquiler, name="enviar_correo_alquiler"),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index_view, name='home'),
]

eventos/urls.py
from django.urls import path
from . import views

app_name = "eventos"

urlpatterns = [
    path("", views.eventos, name="eventos"),
    path("<int:id>/", views.evento_detalle, name="evento_detalle"),
    path("categorias", views.tipos_eventos, name="categorias"),
    path("categorias/<int:id>", views.tipo_evento, name="categoria-evento"),
]

servicios/urls.py
from django.urls import path
from . import views

app_name = "servicios"

urlpatterns = [
    path("", views.servicios, name="servicios"),
    path("<int:id>/", views.servicio_detalle, name="servicio_detalle"),
    

]

tinocoLoco/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('servicios/', include('servicios.urls')),
    path('eventos/', include('eventos.urls')),
    path('alquileres/', include('alquileres.urls')),
]

usuarios/urls.py
from django.urls import path

from . import views

app_name = "usuarios"

urlpatterns = [
    path("crear-cuenta/", views.crear_cuenta, name="crear_cuenta"),
    path("iniciar-sesion/", views.iniciar_sesion, name="iniciar_sesion"),
    path("validar-correo/", views.validar_correo, name="validar_correo"),
    path("perfil/", views.perfil, name="perfil"),
    path("cerrar-sesion/", views.cerrar_sesion, name="cerrar_sesion"),
    path('validar-correo-helper/', views.reenvio_correo_validacion, name='reenvio_correo_validacion'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from eventos.models import TipoEvento
from alquileres.models import Promocion
# Create your views here.

def index_view(request):

    promociones = Promocion.objects.all()[:5]

    tipo_eventos = TipoEvento.objects.all()[:5]

    return render(request, 'core/home.html', {'tipo_eventos': tipo_eventos, 'promociones': promociones})

core/templates/core/components/layout/footer.html
{% load static %}
<footer class="bg-dark" id="tempaltemo_footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 pt-5">
                <h2 class="h2 text-success border-bottom pb-3 border-light logo">{{ configuracion_negocio.nombre }}</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li>
                        <i class="fas fa-map-marker-alt fa-fw"></i>
                        {{ configuracion_negocio.direccion }}
                    </li>
                    <li>
                        <i class="fa fa-phone fa-fw"></i>
                        <a class="text-decoration-none"
                           href="tel:{{ configuracion_negocio.telefono }}">{{ configuracion_negocio.telefono }}</a>
                    </li>
                    <li>
                        <i class="fa fa-envelope fa-fw"></i>
                        <a class="text-decoration-none"
                           href="mailto:{{ configuracion_negocio.correo }}">{{ configuracion_negocio.correo }}</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4 pt-5">
                <h2 class="h2 text-light border-bottom pb-3 border-light">Eventos más populares</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    {% for evento in eventos_mas_gustados %}
                        <li>
                            <a class="text-decoration-none"
                               href="{% url 'eventos:evento_detalle' evento.id %}">{{ evento.nombre }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-auto">
                <img src="{% static 'img/logo_uleam.png' %}"
                     alt="Logo"
                     class="img-fluid"
                     style="max-height: 350px">
            </div>
        </div>

        <div class="row text-light mb-4">
            <div class="col-12 mb-3">
                <div class="w-100 my-3 border-top border-light"></div>
            </div>
            <div class="col-auto me-auto">
                <ul class="list-inline text-left footer-icons">
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none"
                           target="_blank"
                           href="{% if configuracion_negocio.red_social_facebook %}{{ configuracion_negocio.red_social_facebook }}{% else %}# {% endif %}">
                            <i class="fab fa-facebook-f fa-lg fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none"
                           target="_blank"
                           href="{% if configuracion_negocio.red_social_instagram %}{{ configuracion_negocio.red_social_instagram }}{% else %}# {% endif %}">
                            <i class="fab fa-instagram fa-lg fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none"
                           target="_blank"
                           href="{% if configuracion_negocio.red_social_x %}{{ configuracion_negocio.red_social_x }}{% else %}# {% endif %}">
                            <i class="fab fa-twitter fa-lg fa-fw"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>


    </div>
    <div class="w-100 bg-black py-3">
        <div class="container">
            <div class="row pt-2">
                <div class="col-12">
                    <p class="text-left text-light">
                        Copyright &copy; 2021 {{ configuracion_negocio.nombre }}
                        | Designed by <a rel="sponsored" href="https://templatemo.com" target="_blank">{{ configuracion_negocio.nombre }}</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/templatemo.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</footer>

core/templates/core/components/layout/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{configuracion_negocio.nombre}}</title>

    <link rel="apple-touch-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% if configuracion_negocio.logo.url %} {{ configuracion_negocio.logo.url }} {% else %} https://lesquel.github.io/staticSaul/img/favicon.ico {% endif %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">

</head>

core/templates/core/components/layout/header.html
<nav class="navbar navbar-expand-lg navbar-light shadow-sm " style="position: sticky; top: 0; z-index: 10; background-color: #efefef;">
    <div class="container d-flex justify-content-between align-items-center">
        <!-- Brand Logo or Name -->
        <a class="navbar-brand text-success h1 align-self-center"
           href="{% url 'core:home' %}">
            {% if configuracion_negocio.logo %}
                <img src="{{ configuracion_negocio.logo.url }}"
                     alt="{{ configuracion_negocio.nombre }}"
                     style="max-height: 50px;
                            border-radius: 5px">
            {% else %}
                <span class="fw-bold">{{ configuracion_negocio.nombre }}</span>
            {% endif %}
        </a> 
        <!-- Toggle Button for Mobile -->
        <button class="navbar-toggler border-0"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#templatemo_main_nav"
                aria-controls="templatemo_main_nav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navigation Links -->
        <div class="collapse navbar-collapse justify-content-between align-items-center"
             id="templatemo_main_nav">
            <ul class="nav navbar-nav mx-lg-auto">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'core:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link text-dark dropdown-toggle"
                       href="#"
                       id="userDropdown"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">Eventos</a>
                    <ul class="dropdown-menu dropdown-menu-end"
                        aria-labelledby="userDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'eventos:eventos' %}">Ver Eventos</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'eventos:categorias' %}">Ver categorias de evento</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'servicios:servicios' %}">Servicios</a>
                </li>
                {% if not request.user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'alquileres:alquileres' %}">
                            {% if request.user.is_superuser %}
                                Reservas de eventos
                            {% else %}
                                Mis Reservas
                            {% endif %}
                        </a>
                    </li>
                {% endif %}
            </ul>
            <!-- Icons Section -->
            <div class="d-flex align-items-center">
                {% comment %} <a class="nav-icon text-decoration-none d-lg-inline me-3" href="#" data-bs-toggle="modal" data-bs-target="#templatemo_search">
                    <i class="fa fa-fw fa-search text-dark"></i>
                </a> {% endcomment %}
                {% if request.user.is_anonymous %}
                    <a class="btn btn-outline me-3"
                       href="{% url 'usuarios:iniciar_sesion' %}">Iniciar Sesión</a>
                    <a class="btn btn-success text-white me-3"
                       href="{% url 'usuarios:crear_cuenta' %}">Crear Cuenta</a>
                {% else %}
                    <div class="dropdown">
                        <a class="nav-icon text-decoration-none position-relative me-3 dropdown-toggle"
                           href="#"
                           id="userDropdown"
                           role="button"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Perfil
                            <i class="fa fa-fw fa-user text-dark"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end"
                            aria-labelledby="userDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'usuarios:perfil' %}">
                                    Ver Perfil <i class="fa fa-fw fa-user text-dark"></i>
                                </a>
                            </li>
                            {% if request.user.is_superuser %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:index' %}">
                                        Panel de Control <i class="fa fa-fw fa-cogs text-dark"></i>
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a class="dropdown-item" href="{% url 'usuarios:cerrar_sesion' %}">
                                    Cerrar Sesión
                                    <i class="fa fa-fw fa-sign-out-alt text-dark"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

core/templates/core/components/layout/modal.html
<div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="w-100 pt-1 mb-5 text-right">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="" method="get" class="modal-content modal-body border-0 p-0">
            <div style="display: flex; justify-content: center; align-items: center; gap: 2em;" class="input-group mb-2">
                <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                <select  name="tipo_busqueda" class="form-select" aria-label="Default select example">
                    <option value="1">Eventos</option>
                    <option value="2">Sevicios</option>
                </select>
                <button type="submit" class="input-group-text bg-success text-light">
                    <i class="fa fa-fw fa-search text-white"></i>
                </button>
            </div>
        </form>
    </div>
</div>

core/templates/core/components/layout/nav.html
<nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block"
     id="templatemo_nav_top">
    <div class="container text-light">
        <div class="w-100 d-flex justify-content-between">
            <div>
                <i class="fa fa-envelope mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none"
                   href="mailto:info@company.com">{{ configuracion_negocio.correo }}</a>
                <i class="fa fa-phone mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none"
                   href="tel:010-020-0340">{{ configuracion_negocio.telefono }}</a>
            </div>
            <div>
                <a class="text-light"
                   href="{% if configuracion_negocio.pagina_web %}{{ configuracion_negocio.red_social_facebook }}{% else %}# {% endif %}"
                   target="_blank"
                   rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                <a class="text-light"
                   href="{% if configuracion_negocio.red_social_instagram %}{{ configuracion_negocio.red_social_instagram }}{% else %}# {% endif %}"
                   target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                <a class="text-light"
                   href="{% if configuracion_negocio.red_social_x %}{{ configuracion_negocio.red_social_x }}{% else %}# {% endif %}"
                   target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
            </div>
        </div>
    </div>
</nav>