alquileres/urls.py
from django.urls import path
from . import views

app_name = "alquileres"

urlpatterns = [
    path("", views.alquileres, name="alquileres"),
    path("nuevo/<int:item_id>", views.nuevo_alquiler, name="nuevo_alquiler"),
    path("<int:id>/", views.alquiler_detalle, name="alquiler_detalle"),
    path("confirmar/<int:id>", views.confirmar_alquiler, name="confirmar_alquiler"),
    path("enviar-correo/<int:id>", views.enviar_correo_alquiler, name="enviar_correo_alquiler"),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index_view, name='home'),
]

eventos/urls.py
from django.urls import path
from . import views

app_name = "eventos"

urlpatterns = [
    path("", views.eventos, name="eventos"),
    path("<int:id>/", views.evento_detalle, name="evento_detalle"),
    path("categorias", views.tipos_eventos, name="categorias"),
    path("categorias/<int:id>", views.tipo_evento, name="categoria-evento"),
]

tinocoLoco/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('servicios/', include('servicios.urls')),
    path('eventos/', include('eventos.urls')),
    path('alquileres/', include('alquileres.urls')),
]

eventos/models/calificacion_evento.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .evento import Evento


class CalificacionEvento(models.Model):
    class Meta:
        verbose_name = "Calificación de Evento"
        verbose_name_plural = "Calificaciones de Eventos"
        constraints = [
            models.UniqueConstraint(
                fields=["usuario", "evento"],
                name="unique_calificacion_evento",
                violation_error_message="Ya has calificado este evento.",
            )
        ]

    evento = models.ForeignKey(
        Evento,
        on_delete=models.CASCADE,
        related_name="calificacion_evento",
        verbose_name="Evento",
    )
    usuario = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="calificacion_evento",
        verbose_name="Usuario",
    )
    calificacion = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        verbose_name="Calificación",
    )
    comentario = models.TextField(verbose_name="Comentario")
    fecha_publicacion = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de Publicación"
    )

    def __str__(self):
        return f"{self.usuario} - {self.evento} - {self.fecha_publicacion}"

eventos/models/evento.py
from django.db import models
from .tipo_evento import TipoEvento

class Evento(models.Model):
    class Meta:
        verbose_name = 'Evento'
        verbose_name_plural = 'Eventos'
    nombre = models.CharField(max_length=100, default='Nombre del evento', verbose_name='Nombre')
    descripcion = models.CharField(max_length=500, default='Descripción del evento', verbose_name='Descripción')
    valor_referencial = models.FloatField(default=0.0, verbose_name='Valor Referencial')
    numero_horas_permitidas = models.IntegerField(default=0, verbose_name='Número de Horas Permitidas')
    valor_extra_hora = models.FloatField(default=0.0, verbose_name='Valor Extra por Hora')
    tipo_evento = models.ForeignKey(TipoEvento, on_delete=models.CASCADE, verbose_name='Tipo de Evento')

    
    def __str__(self) -> str:
        return f"{self.nombre}"

eventos/models/foto_evento.py
from django.db import models
from cloudinary.models import CloudinaryField
from .evento import Evento
import cloudinary
from django.utils.html import format_html


class FotoEvento(models.Model):
    class Meta:
        verbose_name = "Foto del Evento"
        verbose_name_plural = "Fotos de los Eventos"
        ordering = ["fecha_publicacion"]

    evento = models.ForeignKey(
        Evento, on_delete=models.CASCADE, related_name="fotos", verbose_name="Evento"
    )
    foto = CloudinaryField("Foto", blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True, verbose_name="Descripción")
    fecha_publicacion = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de Publicación"
    )
    numero_likes = models.IntegerField(default=0, verbose_name="Número de Likes")

    def dar_like(self):
        self.numero_likes += 1
        self.save()

    def __str__(self):
        return f"Foto de {self.evento}"

    def get_img(self):
        if self.foto:
            url = cloudinary.utils.cloudinary_url(
                self.foto.public_id, format="jpg", width=100, height=100, crop="fill"
            )[0]
            return f'<img src="{url}" alt="Demo Image" style="border-radius: 5px;" />'
        return "<span>No image available</span>"

    @property
    def foto_view(self):
        html = self.get_img()
        return format_html(html)

eventos/models/tipo_evento.py
from django.db import models
from cloudinary.models import CloudinaryField


class TipoEvento(models.Model):
    class Meta:
        verbose_name = "Tipo de Evento"
        verbose_name_plural = "Tipos de Eventos"
    nombre_evento = models.CharField(max_length=100, verbose_name="Nombre del Evento")
    descripcion = models.TextField(verbose_name="Descripción")
    fecha_creacion = models.DateField(auto_now_add=True, verbose_name="Fecha de Creación")
    imagen = CloudinaryField('Foto', blank=True, null=True)
    
    def __str__(self) -> str:
        return f"{self.nombre_evento}"

eventos/forms/calificacion_evento.py
from django import forms
from ..models import CalificacionEvento


class CalificacionEventoFormulario(forms.ModelForm):
    calificacion = forms.IntegerField(label="Calificación", required=True)
    comentario = forms.CharField(label="Comentario", required=True)

    class Meta:
        model = CalificacionEvento
        fields = ["calificacion", "comentario"]
        widgets = {
            "comentario": forms.Textarea(
                attrs={"rows": 4, "cols": 40, "class": "col-md-12"}
            ),
        }


    def clean_calificacion(self):
        calificacion = self.cleaned_data.get("calificacion")
        if calificacion < 1 or calificacion > 5:
            raise forms.ValidationError(
                "La calificación debe ser un número entre 1 y 5."
            )
        return calificacion

eventos/forms/evento.py
from django import forms
from ..models import Evento  

class EventoFormulario(forms.ModelForm):
    nombre = forms.CharField(max_length=100)
    descripcion = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        required=False
    )
    class Meta:
        model = Evento
        fields = [
            "nombre",
            "descripcion",
            "valor_referencial",
            "numero_horas_permitidas",
            "valor_extra_hora",
            "tipo_evento",
        ]

    def clean_valor_referencial(self):
        valor_referencial = self.cleaned_data.get("valor_referencial")
        if valor_referencial < 0:
            raise forms.ValidationError(
                "El valor referencial no puede ser negativo."
            )
        return valor_referencial

    def clean_valor_extra_hora(self):
        valor_extra_hora = self.cleaned_data.get("valor_extra_hora")
        if valor_extra_hora < 0:
            raise forms.ValidationError(
                "El valor extra por hora no puede ser negativo."
            )
        return valor_extra_hora

    

eventos/forms/foto_evento.py
from django import forms
from ..models import FotoEvento  

class FotoEventoFormulario(forms.ModelForm):
    foto = forms.ImageField(label='Foto', required=True, widget=forms.FileInput(attrs={'class': 'form-control', 'accept': 'image/*'}))
    descripcion = forms.CharField(label='Descripción', required=False, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))
    class Meta:
        model = FotoEvento
        fields = ['evento', 'foto', 'descripcion']


    def clean_foto(self):
        foto = self.cleaned_data.get('foto')
        if not foto:
            raise forms.ValidationError("Debe cargar una foto.")
        return foto

eventos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponseForbidden
from django.db.models import Q, Avg
from .models import Evento, TipoEvento
from .forms import CalificacionEventoFormulario


def eventos(request):
    query = request.GET.get("query", "")
    eventos = Evento.objects.prefetch_related("fotos", "calificacion_evento")

    if query:
        eventos = eventos.filter(
            Q(nombre__icontains=query) | Q(descripcion__icontains=query)
        )

    eventos_data = [
        {
            "evento": evento,
            "imagen_url": (
                evento.fotos.first().foto.url if evento.fotos.exists() else None
            ),
            "promedio_calificaciones": range(
                0,
                int(
                    evento.calificacion_evento.aggregate(Avg("calificacion"))[
                        "calificacion__avg"
                    ]
                    or 0
                ),
            ),
        }
        for evento in eventos
    ]

    return render(request, "eventos/eventos.html", {"eventos": eventos_data})


def tipos_eventos(request):
    tipos_eventos = TipoEvento.objects.all()
    return render(
        request, "eventos/tipos_eventos.html", {"tipos_eventos": tipos_eventos}
    )


def tipo_evento(request, id):
    tipo_evento = get_object_or_404(TipoEvento, id=id)
    eventos = Evento.objects.filter(tipo_evento=tipo_evento).prefetch_related(
        "fotos", "calificacion_evento"
    )

    eventos_data = [
        {
            "evento": evento,
            "imagen_url": (
                evento.fotos.first().foto.url if evento.fotos.exists() else None
            ),
            "promedio_calificaciones": range(
                0,
                int(
                    evento.calificacion_evento.aggregate(Avg("calificacion"))[
                        "calificacion__avg"
                    ]
                    or 0
                ),
            ),
        }
        for evento in eventos
    ]

    return render(
        request,
        "eventos/tipo_evento.html",
        {"tipo_evento": tipo_evento, "eventos": eventos_data},
    )


def evento_detalle(request, id):
    evento = get_object_or_404(
        Evento.objects.prefetch_related("fotos", "calificacion_evento"), id=id
    )

    promedio_calificaciones = (
        evento.calificacion_evento.aggregate(Avg("calificacion"))["calificacion__avg"]
        or 0
    )

    # Handle form submission
    if request.method == "POST":
        if not request.user.is_authenticated:
            return redirect("usuarios:iniciar_sesion")

        formulario = CalificacionEventoFormulario(request.POST)
        if formulario.is_valid():
            if evento.calificacion_evento.filter(usuario=request.user).exists():
                messages.warning(request, "Ya has calificado este evento.")
                return redirect("eventos:evento_detalle", id=id)

            calificacion = formulario.save(commit=False)
            calificacion.evento = evento
            calificacion.usuario = request.user
            calificacion.save()
            messages.success(request, "Calificación registrada con éxito.")
            return redirect("eventos:evento_detalle", id=id)
        else:
            messages.error(request, "Error al registrar la calificación.")
    else:
        formulario = CalificacionEventoFormulario(
            initial={
                "evento": evento.id,
                "usuario": request.user.id if request.user.is_authenticated else None,
            }
        )

    return render(
        request,
        "eventos/detalle_evento.html",
        {
            "evento": evento,
            "promedio_range": range(0, int(promedio_calificaciones)),
            "promedio_calificaciones": round(promedio_calificaciones, 1),
            "fotos": evento.fotos.all(),
            "calificaciones": evento.calificacion_evento.all(),
            "form": formulario,
        },
    )

eventos/templates/eventos/components/detalle.html
<section class=" py-5">
    <div class="container " style="width: 100%;">
        <section class="bg-light">
            <div class="container pb-5">
                <div class="row">
                    <div class="col-lg-5 mt-5"
                         style="display: flex;
                                justify-content: center;
                                align-items: center;
                                gap: 2em">
                        <div class="card mb-3">{% include 'core/components/utils/carrucel.html' with fotos=fotos %}</div>
                    </div>
                    <!-- col end -->
                    <div class="col-lg-7 mt-5">
                        <div class="card">
                            <div class="card-body">
                                <h1 class="h2">{{ item.nombre }}</h1>
                                <p class="h3 py-2">{{ valor_referencial }}</p>
                                <p class="py-2">
                                    {% for i in promedio_range %}<i class="fa fa-star text-warning"></i>{% endfor %}
                                    <span class="list-inline-item text-dark">{{ promedio_calificaciones }} de 5,0</span>
                                </p>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <h6>Tipo evento:</h6>
                                    </li>
                                    <li class="list-inline-item">
                                        <p class="text-muted">
                                            <strong>{{ item.tipo_evento }}</strong>
                                        </p>
                                    </li>
                                </ul>
                                <h6>Description:</h6>
                                <p>{{ item.descripcion }}</p>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <h6>Horas permitidas :</h6>
                                    </li>
                                    <li class="list-inline-item">
                                        <p class="text-muted">
                                            <strong>{{ item.numero_horas_permitidas }}</strong>
                                        </p>
                                    </li>
                                </ul>
                                <h6>Valor extra por hora :</h6>
                                <ul class="list-unstyled pb-3">
                                    <li>{{ item.valor_extra_hora }}</li>
                                </ul>
                                <div class="row pb-3">
                                    <div class="col d-grid">
                                        <a href="{% url 'alquileres:nuevo_alquiler' item.id %}"
                                           class="btn btn-success btn-lg">Alquilar</a>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</section>