core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index_view, name='home'),
]

tinocoLoco/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('servicios/', include('servicios.urls')),
    path('eventos/', include('eventos.urls')),
    path('alquileres/', include('alquileres.urls')),
]

usuarios/urls.py
from django.urls import path

from . import views

app_name = "usuarios"

urlpatterns = [
    path("crear-cuenta/", views.crear_cuenta, name="crear_cuenta"),
    path("iniciar-sesion/", views.iniciar_sesion, name="iniciar_sesion"),
    path("validar-correo/", views.validar_correo, name="validar_correo"),
    path("perfil/", views.perfil, name="perfil"),
    path("cerrar-sesion/", views.cerrar_sesion, name="cerrar_sesion"),
    path('validar-correo-helper/', views.reenvio_correo_validacion, name='reenvio_correo_validacion'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string


class PerfilUsuario(models.Model):
    class Meta:
        verbose_name = "Perfil de Usuario"
        verbose_name_plural = "Perfiles de Usuario"

    usuario = models.OneToOneField(
        User, on_delete=models.CASCADE, verbose_name="Usuario"
    )
    identificacion_cliente = models.CharField(
        max_length=10,
        unique=True,
        blank=True,
        null=True,
        verbose_name="Identificación del Cliente",
    )
    nacionalidad = models.CharField(
        max_length=50, blank=True, null=True, verbose_name="Nacionalidad"
    )
    fecha_registro = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de Registro"
    )
    telefono = models.CharField(
        max_length=10, blank=True, null=True, verbose_name="Teléfono"
    )
    nombres = models.CharField(
        max_length=100, blank=True, null=True, verbose_name="Nombres"
    )
    apellidos = models.CharField(
        max_length=100, blank=True, null=True, verbose_name="Apellidos"
    )
    correo_electronico = models.CharField(
        max_length=100, blank=True, null=True, verbose_name="Correo Electrónico"
    )
    genero = models.CharField(
        max_length=50,
        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
        blank=True,
        null=True,
        verbose_name="Género",
    )
    fecha_nacimiento = models.DateField(
        blank=True, null=True, verbose_name="Fecha de Nacimiento"
    )
    codigo_verificacion = models.CharField(
        max_length=6, blank=True, null=True, verbose_name="Código de Verificación"
    )
    correo_electronico_verificado = models.BooleanField(
        default=False, verbose_name="Correo Electrónico Verificado"
    )
    @property
    def datos_completos(self):
        campos_requeridos = [
            self.nombres,
            self.apellidos,
            self.nacionalidad,
            self.telefono,
            self.fecha_nacimiento,
            self.correo_electronico,
        ]
        return all(campos_requeridos) and self.correo_electronico_verificado
    def __str__(self):
        return self.usuario.username

    def generar_codigo_verificacion(self):
        self.codigo_verificacion = get_random_string(length=6)

usuarios/forms/actualizar_perfil.py
from django import forms
from usuarios.models import PerfilUsuario


class ActualizarPerfilFormulario(forms.ModelForm):
    nacionalidad = forms.CharField(
        label="Nacionalidad",
        widget=forms.TextInput(attrs={"required": "required"}),
    )
    telefono = forms.CharField(
        label="Teléfono",
        widget=forms.TextInput(attrs={"required": "required"}),
    )
    nombres = forms.CharField(
        label="Nombres",
        widget=forms.TextInput(attrs={"required": "required"}),
    )
    apellidos = forms.CharField(
        label="Apellidos",
        widget=forms.TextInput(attrs={"required": "required"}),
    )

    genero = forms.ChoiceField(
        label="Género",
        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
        widget=forms.Select(attrs={"required": "required"}),
    )

    fecha_nacimiento = forms.DateField(
        label="Fecha de nacimiento",
        widget=forms.DateInput(attrs={"type": "date", "required": "required"}),
    )

    class Meta:
        model = PerfilUsuario
        fields = [
            "nacionalidad",
            "telefono",
            "nombres",
            "apellidos",
            "genero",
            "fecha_nacimiento",
        ]

    def clean_identificacion_cliente(self):
        identificacion_cliente = self.cleaned_data.get("identificacion_cliente")
        if identificacion_cliente != self.instance.identificacion_cliente:
            raise forms.ValidationError(
                "No puedes cambiar tu número de identificación."
            )
        return identificacion_cliente

    def clean_correo_electronico(self):
        correo_electronico = self.cleaned_data.get("correo_electronico")
        if correo_electronico != self.instance.correo_electronico:
            raise forms.ValidationError("No puedes cambiar tu correo electrónico.")
        return correo_electronico

usuarios/forms/completar_perfil.py
from django import forms
from usuarios.models import PerfilUsuario


class CompletarPerfilFormulario(forms.ModelForm):
    identificacion_cliente = forms.CharField(
        label="Identificación",
        widget=forms.TextInput(attrs={"required": "required"}),
    )
    nacionalidad = forms.CharField(
        label="Nacionalidad",
        widget=forms.TextInput(attrs={"required": "required"}),
    )
    telefono = forms.CharField(
        label="Teléfono",
        widget=forms.TextInput(attrs={"required": "required"}),
    )
    nombres = forms.CharField(
        label="Nombres",
        widget=forms.TextInput(attrs={"required": "required"}),
    )
    apellidos = forms.CharField(
        label="Apellidos",
        widget=forms.TextInput(attrs={"required": "required"}),
    )
    correo_electronico = forms.EmailField(
        label="Correo electrónico",
        widget=forms.EmailInput(attrs={"required": "required"}),
    )
    genero = forms.ChoiceField(
        label="Género",
        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
        widget=forms.Select(attrs={"required": "required"}),
    )
    fecha_nacimiento = forms.DateField(
        label="Fecha de nacimiento",
        widget=forms.DateInput(attrs={"type": "date", "required": "required"}),
    )

    class Meta:
        model = PerfilUsuario
        fields = [
            "identificacion_cliente",
            "nacionalidad",
            "telefono",
            "nombres",
            "apellidos",
            "correo_electronico",
            "genero",
            "fecha_nacimiento",
        ]

    def clean_identificacion_cliente(self):
        identificacion_cliente = self.cleaned_data.get("identificacion_cliente")
        if (
            PerfilUsuario.objects.filter(
                identificacion_cliente=identificacion_cliente
            ).exists()
            and not PerfilUsuario.objects.filter(
                identificacion_cliente=identificacion_cliente,
                usuario=self.instance.usuario,
            ).exists()
        ):
            raise forms.ValidationError("Este número de identificación ya está en uso.")
        return identificacion_cliente

usuarios/forms/crear_cuenta.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from utilidades import EmailEnviador
from ..models import PerfilUsuario


class CrearCuentaFormulario(UserCreationForm):
    username = forms.CharField(
        label="Usuario",
        widget=forms.TextInput(attrs={"placeholder": "Ingrese su usuario"}),
    )

    email = forms.EmailField(
        label="Correo electrónico",
        widget=forms.EmailInput(attrs={"placeholder": "Ingrese su correo electrónico"}),
        error_messages={"unique": "El correo electrónico ya está en uso."},
    )

    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={"placeholder": "Ingrese su contraseña"}),
    )

    password2 = forms.CharField(
        label="Confirmar contraseña",
        widget=forms.PasswordInput(attrs={"placeholder": "Confirme su contraseña"}),
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if not username.isalnum():
            raise forms.ValidationError(
                "El usuario solo puede contener letras y números."
            )
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("El nombre de usuario ya existe.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("El correo electrónico ya está en uso.")
        return email

    def save(self, commit=True):
        user = super().save(commit=commit)
        perfil = PerfilUsuario.objects.create(
            usuario=user, correo_electronico=self.cleaned_data["email"]
        )
        perfil.generar_codigo_verificacion()
        perfil.save()

        EmailEnviador.enviar_codigo_validar_email(perfil)
        return user

usuarios/forms/iniciar_sesion.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User


class IniciarSesionFormulario(AuthenticationForm):
    username = forms.CharField(label="Usuario",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Ingrese su usuario",
            }
        )
    )

    password = forms.CharField(label="Contraseña",
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Ingrese su contraseña",
            }
        )
    )

    class Meta:
        model = User
        fields = (
            "username",
            "password",
        )


    def clean_username(self):
        username = self.cleaned_data.get("username")
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                "El usuario no existe", code="username_not_found"
            )
        return username

    def clean_password(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if User.objects.filter(username=username).exists():
            user = User.objects.get(username=username)
            if not user.check_password(password):
                raise forms.ValidationError(
                    "La contraseña es incorrecta", code="invalid_password"
                )
        return password

usuarios/forms/validar_correo.py
from django import forms
from usuarios.models import PerfilUsuario


class ValidarCorreoFormulario(forms.Form):
    codigo_verificacion = forms.CharField(
        label="Código de verificación",
        widget=forms.TextInput(attrs={"placeholder": "Ingrese el código de verificación"}),
    )
    
    class Meta:
        fields = ("codigo_verificacion",)
    

    def clean(self):
        cleaned_data = super().clean()
        codigo_verificacion = cleaned_data.get("codigo_verificacion")

        user = self.user
        perfil = PerfilUsuario.objects.filter(usuario=user).first()

        if not perfil:
            raise forms.ValidationError("No se encontró un perfil asociado a este usuario.")

        if perfil.codigo_verificacion != codigo_verificacion:
            raise forms.ValidationError("El código de verificación es incorrecto.")

        if perfil.correo_electronico_verificado:
            raise forms.ValidationError("Este correo ya ha sido verificado.")

        return cleaned_data
    
    def save(self):
        perfil = PerfilUsuario.objects.get(usuario=self.user)
        perfil.correo_electronico_verificado = True
        perfil.save()
        return perfil

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from utilidades import EmailEnviador
from django.http import JsonResponse

from .forms import (
    CrearCuentaFormulario,
    IniciarSesionFormulario,
    ValidarCorreoFormulario,
    CompletarPerfilFormulario,
)

from .models import PerfilUsuario
from utilidades import ValidadorUsuario


def crear_cuenta(request):
    if request.user.is_authenticated:
        return redirect("usuarios:perfil")
    if request.method == "POST":
        form = CrearCuentaFormulario(request.POST)
        if form.is_valid():
            usuario = form.save()
            login(request, usuario)
            messages.success(request, "Cuenta creada correctamente")
            messages.info(request, "Por favor, verifica tu correo electrónico")
            return redirect("usuarios:perfil")

    else:
        form = CrearCuentaFormulario()
    return render(request, "usuarios/crear_cuenta.html", {"form": form})


def iniciar_sesion(request):
    if request.user.is_authenticated:
        return redirect("usuarios:perfil")
    if request.method == "POST":

        form = IniciarSesionFormulario(data=request.POST)
        if form.is_valid():
            usuario = form.get_user()
            login(request, usuario)

            return redirect("core:home")
    else:
        form = IniciarSesionFormulario()
    return render(request, "usuarios/iniciar_sesion.html", {"form": form})


@login_required
def cerrar_sesion(request):
    if request.method == "GET":
        logout(request)
        return redirect("usuarios:iniciar_sesion")


@login_required
def validar_correo(request):
    try:
        usuario = request.user
        if ValidadorUsuario.validar_correo_verificado(usuario):
            return redirect("usuarios:perfil")
        
        if request.method == "POST":
            form = ValidarCorreoFormulario(data=request.POST)
            form.user = usuario
            if form.is_valid():
                form.save()
                return JsonResponse({"success": True, "message": "Correo verificado correctamente."})
            return JsonResponse({"success": False, "errors": form.errors}, status=400)
        else:
            return JsonResponse({"success": False, "message": "Método no permitido."}, status=405)
    except Exception as e:
        # Imprime el error en los logs para depurar
        print(f"Error en validar_correo: {str(e)}")
        return JsonResponse({"success": False, "message": "Error interno del servidor."}, status=500)


@login_required
def perfil(request):
    usuario = request.user
    perfil = PerfilUsuario.objects.get_or_create(usuario=usuario)[0]

    formulario_validar_correo = ValidarCorreoFormulario()

    if request.method == "POST":
        formulario = CompletarPerfilFormulario(request.POST, instance=perfil)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Perfil actualizado correctamente")
    else:
        formulario = CompletarPerfilFormulario(instance=perfil)

    return render(
        request,
        "usuarios/perfil.html",
        {
            "usuario": perfil,
            "form": formulario,
            "form_validar_correo": formulario_validar_correo,
        },
    )


@login_required
def reenvio_correo_validacion(request):

    perfil_usuario = PerfilUsuario.objects.get(usuario=request.user)

    perfil_usuario.generar_codigo_verificacion()
    perfil_usuario.save()

    EmailEnviador.enviar_codigo_validar_email(perfil_usuario)

    return JsonResponse(
        {"success": True, "message": "Correo de validación enviado nuevamente."}
    )




@login_required
def validar_correo(request):
    usuario = request.user
    if ValidadorUsuario.validar_correo_verificado(usuario):
        messages.info(request, "Correo ya verificado")
        return redirect("usuarios:perfil")

    if request.method == "POST":
        print(request.POST)
        form = ValidarCorreoFormulario(data=request.POST)
        form.user = usuario
        if form.is_valid():
            form.save()
            messages.success(request, "Correo verificado correctamente")
            return redirect("usuarios:perfil")
        messages.error(request, "Código de verificación incorrecto")
    else:
        form = ValidarCorreoFormulario()

    return render(request, "usuarios/validar_correo.html", {"form": form})

usuarios/templates/usuarios/crear_cuenta.html
{% extends "usuarios/layout/base.html" %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="d-flex justify-content-center align-items-center"
         style="min-height: 100vh">
        <div class="card p-4 shadow-sm"
             style="max-width: 500px;
                    width: 100%;
                    margin-top: -10vh">
            <h2 class="text-center mb-4">Registrarse</h2>
            <form method="post" class="form-group">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success w-100">Crear cuenta</button>
            </form>
            <p class="text-center mt-3">
                ¿Ya tienes una cuenta?
                <a href="{% url 'usuarios:iniciar_sesion' %}">Iniciar sesion</a>
            </p>
        </div>
    </div>
{% endblock content %}

usuarios/templates/usuarios/iniciar_sesion.html
{% extends "usuarios/layout/base.html" %}
{% block content %}
    {% load static %}
    {% load crispy_forms_tags %}
    <section class="py-5">
        <div class="d-flex justify-content-center align-items-center"
         style="min-height: 100vh">
        <div class="card p-4 shadow-sm"
             style="max-width: 500px;
                    width: 100%;
                    margin-top: -10vh">
            <h2 class="text-center mb-4">Iniciar Sesión</h2>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}    
            {% endif %}

            <form method="post" class="form-group">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success w-100">Iniciar Sesión</button>
            </form>
            <p class="text-center mt-3">
                ¿No tienes una cuenta?
                <a href="{% url 'usuarios:crear_cuenta' %}">Crear cuenta</a>
            </p>
        </div>
    </div>
    </section>
{% endblock content %}

usuarios/templates/usuarios/perfil.html
{% extends "usuarios/layout/base.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container mt-5">
    <div class="main-body">
        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="Admin"
                                class="rounded-circle p-1 bg-primary" width="110">
                            <div class="mt-3">
                                <h4>{{ usuario }}</h4>
                                <p class="text-secondary mb-1">{{ usuario.identificacion_cliente }}</p>
                                <p class="text-muted font-size-sm">Correo: {{ usuario.correo_electronico }}</p>
                                {% if usuario.datos_completos %}
                                <span class="text-success">
                                    <i class="fas fa-check-circle"></i> Datos Completos
                                </span>
                                {% else %}
                                <span class="text-danger">
                                    <i class="fas fa-times-circle"></i> Datos Incompletos
                                </span>
                                {% endif %}
                                <hr class="my-2">
                                {% if usuario.correo_electronico_verificado %}
                                <span class="text-success">
                                    <i class="fas fa-check-circle"></i> Verificado
                                </span>
                                {% else %}
                                <span class="text-danger">
                                    <i class="fas fa-times-circle"></i> No Verificado
                                    <hr class="my-2">
                                    <button type="button" class="btn btn-success" data-bs-toggle="modal"
                                        data-bs-target="#staticBackdrop">Verificar Correo</button>
                                </span>
                                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static"
                                    data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
                                    aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="staticBackdropLabel">Validar correo
                                                </h1>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                {% csrf_token %}
                                                {{ form_validar_correo|crispy }}
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-bs-dismiss="modal">Cerrar</button>
                                                <p class="btn btn-dark" id="renviar">Enviar otra vez</p>
                                                <button id="verificar_correo" type="button"
                                                    class="btn btn-success">Validar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card">
                    {% if messages %}
                    <div>
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} mt-3" role="alert">{{ message }}</div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="card-body">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="row">
                                {% for field in form %}
                                <div class="col-md-6 mb-3">{{ field|as_crispy_field }}</div>
                                {% if forloop.counter|divisibleby:2 %}
                            </div>
                            <div class="row">
                                {% endif %}
                                {% endfor %}
                            </div>
                            <div class="row mt-3">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-success w-100 px-4">Actualizar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function enviarCorreoValidacion() {
        const url = "{% url 'usuarios:reenvio_correo_validacion' %}";  // URL de la vista para validar el correo
        fetch(url)
            .then(response => response.json())
            .then(data => {
            })
            .catch(error => {
                console.error(error);
            });
    }


    document.getElementById("renviar").addEventListener("click", enviarCorreoValidacion);

    console.log(document.getElementById("id_codigo_verificacion").value);

    function verificarCorreo() {
        const url = "{% url 'usuarios:validar_correo' %}";  // URL de la vista para validar el correo
        const formData = new FormData();
        formData.append("codigo_verificacion", document.getElementById("id_codigo_verificacion").value);
        console.log("FormData", formData);
        fetch(url, {
            method: 'POST',
            headers: {
                'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value, // Incluimos el CSRF token
            },
            body: formData  // Enviamos los datos como FormData
        })
            .then(response => response.json())
            .then(data => {
                if (data.errors) {
                    alert("Error: " + Object.values(data.errors).join(", "));  // Muestra los errores
                    return
                }
                window.location.reload();
            })
            .catch(error => {
                window.location.reload();
            });
    }

    document.getElementById("verificar_correo").addEventListener("click", verificarCorreo);

</script>
{% endblock content %}

usuarios/templates/usuarios/usuarios.html
{% for perfil in perfils %}
    <div class="perfil">
        <h2>{{=perfil.nombre}}</h2>
        <p>{{=perfil.email}}</p>
    </div>
{% for %}

usuarios/templates/usuarios/validar_correo.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Validar correo</button>
</form>